import { DataTable } from "@/components/refine-ui/data-table/data-table";
import { EmptyCell } from "@/components/refine-ui/empty-cell";
import {
  ListView,
  ListViewHeader,
} from "@/components/refine-ui/views/list-view";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { buildReportCsv, downloadCsv } from "@/lib/report-csv";
import { supabaseClient } from "@/providers/supabase-client";
import type { Tables } from "@/types/database";
import { parseTimeEntrySnapshot } from "@/types/report-snapshot";
import type { HttpError } from "@refinedev/core";
import { useCan, useInvalidate } from "@refinedev/core";
import { useTable } from "@refinedev/react-table";
import { createColumnHelper } from "@tanstack/react-table";
import { format } from "date-fns";
import { Download, Eye, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { ReportPreviewSheet } from "./report-preview-sheet";

export type ReportRow = Tables<"reports"> & {
  profiles: { full_name: string } | null;
};

const columnHelper = createColumnHelper<ReportRow>();

function DownloadButton({ report }: { report: ReportRow }) {
  const [loading, setLoading] = useState(false);

  function handleDownload() {
    setLoading(true);
    try {
      const csv = buildReportCsv(report.time_entries_snapshot);
      const filename = `report_${report.period_start}_${report.period_end}.csv`;
      downloadCsv(csv, filename);
    } catch (e) {
      toast.error("Failed to download report.", { richColors: true });
      console.error(e);
    } finally {
      setLoading(false);
    }
  }

  return (
    <Button variant="ghost" size="icon" disabled={loading} onClick={handleDownload}>
      <Download className="h-4 w-4" />
      <span className="sr-only">Download CSV</span>
    </Button>
  );
}

function DeleteReportButton({ report }: { report: ReportRow }) {
  const [saving, setSaving] = useState(false);
  const invalidate = useInvalidate();
  const { data: canDelete } = useCan({ resource: "reports", action: "write" });
  const entryCount = parseTimeEntrySnapshot(report.time_entries_snapshot).length;

  if (!canDelete?.can) return null;

  async function handleDelete() {
    setSaving(true);
    const { error } = await supabaseClient.rpc("delete_report", {
      p_report_id: report.id,
    });
    setSaving(false);
    if (error) {
      toast.error("Failed to delete report.", { richColors: true });
      console.error(error);
      return;
    }
    toast.success("Report deleted and entries unlocked.", { richColors: true });
    invalidate({ resource: "reports", invalidates: ["list"] });
  }

  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button variant="ghost" size="icon" disabled={saving} aria-label="Delete report">
          <Trash2 className="h-4 w-4" />
        </Button>
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Delete report?</AlertDialogTitle>
          <AlertDialogDescription>
            Deleting this report will unlock all {entryCount} entries and
            permanently remove the snapshot. This cannot be undone.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction onClick={handleDelete}>Delete</AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}

function buildColumns(onPreview: (report: ReportRow) => void) {
  return [
    columnHelper.display({
      id: "period",
      header: "Period",
      size: 220,
      cell: ({ row }) => {
        const { period_start, period_end } = row.original;
        return `${period_start} — ${period_end}`;
      },
    }),
    columnHelper.accessor("generated_at", {
      header: "Generated",
      size: 180,
      cell: ({ getValue }) => {
        const v = getValue();
        return v ? format(new Date(v), "PPp") : <EmptyCell />;
      },
    }),
    columnHelper.display({
      id: "generated_by",
      header: "Generated By",
      size: 200,
      cell: ({ row }) => {
        const name = row.original.profiles?.full_name;
        return name ?? <EmptyCell />;
      },
    }),
    columnHelper.display({
      id: "actions",
      size: 120,
      cell: ({ row }) => (
        <div className="action-column">
          <Button
            variant="ghost"
            size="icon"
            aria-label="Preview report"
            onClick={() => onPreview(row.original)}
          >
            <Eye className="h-4 w-4" />
          </Button>
          <DownloadButton report={row.original} />
          <DeleteReportButton report={row.original} />
        </div>
      ),
    }),
  ];
}

export function ReportList() {
  const [previewReport, setPreviewReport] = useState<ReportRow | null>(null);

  const columns = useMemo(() => buildColumns(setPreviewReport), []);

  const table = useTable<ReportRow, HttpError>({
    columns,
    refineCoreProps: {
      resource: "reports",
      meta: {
        select: "*, profiles(full_name)",
      },
      sorters: {
        initial: [{ field: "generated_at", order: "desc" }],
      },
      pagination: { pageSize: 50 },
    },
  });

  return (
    <ListView className="p-6">
      <ListViewHeader title="Reports" canCreate />
      <DataTable table={table} />
      {previewReport && (
        <ReportPreviewSheet
          open
          onOpenChange={(open) => { if (!open) setPreviewReport(null); }}
          report={previewReport}
        />
      )}
    </ListView>
  );
}
