import { Authenticated, CanAccess, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import type { ComponentProps } from "react";

import routerProvider, {
  DocumentTitleHandler,
  UnsavedChangesNotifier,
} from "@refinedev/react-router";
import { liveProvider } from "@refinedev/supabase";
import { BarChart2, CalendarDays, FileText, Tag, Timer, UserPlus, Users } from "lucide-react";
import { BrowserRouter, Outlet, Route, Routes } from "react-router";
import "./App.css";
import { SignInForm } from "./components/refine-ui/form/sign-in-form";
import { Layout } from "./components/refine-ui/layout/layout";
import { Toaster } from "./components/refine-ui/notification/toaster";
import { useNotificationProvider } from "./components/refine-ui/notification/use-notification-provider";
import { ThemeProvider } from "./components/refine-ui/theme/theme-provider";
import { AnalyticsList } from "./pages/analytics/list";
import { CategoryCreate } from "./pages/categories/create";
import { CategoryList } from "./pages/categories/list";
import { InviteCreate } from "./pages/invites/create";
import { InviteList } from "./pages/invites/list";
import { MemberList } from "./pages/members/list";
import { ReportCreate } from "./pages/reports/create";
import { ReportList } from "./pages/reports/list";
import { MemberWeekView } from "./pages/time-entries/list";
import { accessControlProvider } from "./providers/access-control-provider";
import authProvider from "./providers/auth";
import { dataProvider } from "./providers/data";
import { supabaseClient } from "./providers/supabase-client";

type TitleHandler = NonNullable<ComponentProps<typeof DocumentTitleHandler>["handler"]>;
const customTitleHandler: TitleHandler = (options) =>
  options.autoGeneratedTitle.replace("Refine", "Time Tracker");

function AccessDenied() {
  return (
    <div className="flex flex-col gap-2 p-6">
      <h1 className="text-2xl font-semibold">Access denied</h1>
      <p className="text-muted-foreground">
        You don't have permission to view this page.
      </p>
    </div>
  );
}

function App() {
  return (
    <BrowserRouter>
      <RefineKbarProvider>
        <ThemeProvider>
          <Refine
            dataProvider={dataProvider}
            liveProvider={liveProvider(supabaseClient)}
            authProvider={authProvider}
            accessControlProvider={accessControlProvider}
            routerProvider={routerProvider}
            notificationProvider={useNotificationProvider()}
            resources={[
              {
                name: "time_entries",
                list: "/",
                meta: {
                  label: "My Week",
                  icon: <CalendarDays size={16} />,
                },
              },
              {
                name: "invites",
                list: "/invites",
                create: "/invites/create",
                meta: {
                  label: "Invites",
                  icon: <UserPlus size={16} />,
                  canDelete: true,
                },
              },
              {
                name: "members",
                list: "/members",
                meta: {
                  label: "Members",
                  icon: <Users size={16} />,
                },
              },
              {
                name: "categories",
                list: "/categories",
                create: "/categories/create",
                meta: {
                  label: "Categories",
                  icon: <Tag size={16} />,
                },
              },
              {
                name: "reports",
                list: "/reports",
                create: "/reports/create",
                meta: {
                  label: "Reports",
                  icon: <FileText size={16} />,
                },
              },
              {
                name: "analytics",
                list: "/analytics",
                meta: {
                  label: "Analytics",
                  icon: <BarChart2 size={16} />,
                },
              },
            ]}
            options={{
              syncWithLocation: true,
              warnWhenUnsavedChanges: true,
              liveMode: "auto",
              redirect: { afterCreate: "list" },
              disableTelemetry: true,
              title: { text: "Time Tracker", icon: <Timer /> },
            }}
          >
            <Routes>
              <Route path="/login" element={<SignInForm />} />

              <Route
                element={
                  <Authenticated key="authenticated-layout" redirectOnFail="/login">
                    <Layout>
                      <Outlet />
                    </Layout>
                  </Authenticated>
                }
              >
                <Route
                  index
                  element={
                    <CanAccess
                      resource="time_entries"
                      action="list"
                      fallback={<AccessDenied />}
                    >
                      <MemberWeekView />
                    </CanAccess>
                  }
                />
                <Route
                  path="invites"
                  element={
                    <CanAccess
                      resource="invites"
                      action="list"
                      fallback={<AccessDenied />}
                    >
                      <InviteList />
                    </CanAccess>
                  }
                />
                <Route
                  path="invites/create"
                  element={
                    <CanAccess
                      resource="invites"
                      action="create"
                      fallback={<AccessDenied />}
                    >
                      <InviteCreate />
                    </CanAccess>
                  }
                />
                <Route
                  path="members"
                  element={
                    <CanAccess
                      resource="members"
                      action="list"
                      fallback={<AccessDenied />}
                    >
                      <MemberList />
                    </CanAccess>
                  }
                />
                <Route
                  path="categories"
                  element={
                    <CanAccess
                      resource="categories"
                      action="list"
                      fallback={<AccessDenied />}
                    >
                      <CategoryList />
                    </CanAccess>
                  }
                />
                <Route
                  path="categories/create"
                  element={
                    <CanAccess
                      resource="categories"
                      action="create"
                      fallback={<AccessDenied />}
                    >
                      <CategoryCreate />
                    </CanAccess>
                  }
                />
                <Route
                  path="reports"
                  element={
                    <CanAccess
                      resource="reports"
                      action="list"
                      fallback={<AccessDenied />}
                    >
                      <ReportList />
                    </CanAccess>
                  }
                />
                <Route
                  path="reports/create"
                  element={
                    <CanAccess
                      resource="reports"
                      action="create"
                      fallback={<AccessDenied />}
                    >
                      <ReportCreate />
                    </CanAccess>
                  }
                />
                <Route
                  path="analytics"
                  element={
                    <CanAccess
                      resource="analytics"
                      action="list"
                      fallback={<AccessDenied />}
                    >
                      <AnalyticsList />
                    </CanAccess>
                  }
                />
              </Route>
            </Routes>

            <Toaster />
            <RefineKbar />
            <UnsavedChangesNotifier />
            <DocumentTitleHandler handler={customTitleHandler} />
          </Refine>
        </ThemeProvider>
      </RefineKbarProvider>
    </BrowserRouter>
  );
}

export default App;
